### ISSUE TITLE
PaperSpigot 1.12 FurnitureLib not working

### ISSUE THREAD

**Issue by Fonzee9** [Ste3et/FurnitureLib#27]
https://github.com/PaperMC/Paper/issues/733

**Comment by Ste3et** [comment]
Have you installed the newest furnitureLib version ?

**Comment by Ste3et** [comment]
i have tested Paper version git-Paper-1107 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT) and FurnitureLib: 1.9.2.5 and i have no problems

**Comment by Zbob750** [comment]
Test against the latest version of Paper and you'll find that it doesn't work.

Your plugin uses an internal CraftBukkit logging library to handle InputStreams,

![ex](http://i.imgur.com/76TbPGA.png)

presumably because in MC 1.12, Bukkit removed the old one from YamlConfiguration.

This is bad for a number of reasons, mostly because you have now tied yourself directly to CraftBukkit limiting where your plugin will run, as well as risking breakage if the implementation changes from version to version.

Which is what happened here. Paper recently replaced CraftBukkit's logging system with a better one and now your plugin no longer runs on Paper because of this change.

The correct way to fix this issue is the same way everyone else did, by migrating to newer methods in the API, not using internal CraftBukkit libraries.

Here's an issue ticket for Multiverse-Portals https://github.com/Multiverse/Multiverse-Portals/issues/457 and here is how they _properly_ ended up fixing this issue https://github.com/Multiverse/Multiverse-Portals/commit/3852d2a34da65b660d12ba1f165d73f170a898e5

You need to do the same in order to:
- Maintain better long term compatibility with the API (less updating your plugin)
- Support the latest builds of Paper **and other implementations**

This change would benefit us all, please consider it.
Thanks for your time.

**Comment by Ste3et** [comment]
Thank you i have solve the problem.
