### ISSUE TITLE
serious issue with piston

### ISSUE THREAD

**Issue by disqetow** [Ste3et/FurnitureLib#99]
Lastest FurnitureLibary and DiceFurniture on spigot with paper 1.20.4, player can use piston push furniture
![2024-02-16_22 46 52](https://github.com/Ste3et/FurnitureLib/assets/32502235/ac1afa7f-5b5a-4dfb-8379-bc45de62f56b)
![2024-02-16_22 47 52](https://github.com/Ste3et/FurnitureLib/assets/32502235/16bfb1a0-c3dc-4bbb-9675-a3e12c12ad9f)
![2024-02-16_22 48 20](https://github.com/Ste3et/FurnitureLib/assets/32502235/937c6165-193e-4a36-b8a9-40add18b4053)

some furniture can dupe block by use this.

**Comment by Ste3et** [comment]
The issue with block movement inside Models have been fixed but the ArmorStand movement is an known issue since years.

I have take a look into the issue and its still a client render thing and can't fixed from me.
When you move outside the render distance of the model and come back everything is on the correct location, no certain packet will be sendet or received by server/client on Extend and Retracting of the Furniture Entities.

The clearfiy i try to resend the models with PistonExtend and retract event but pistons wihtout a block didn't trigger a event to catch.

**Comment by disqetow** [comment]
I see you push new version, but I find some issue with it.
if you try push furniture, and broke it, same location sticky piston will not work.
[https://youtu.be/S02hTcSujLQ](url)

**Comment by Ste3et** [comment]
https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.12.x%20-%201.20.x&commit=cf28997b

**Comment by disqetow** [comment]
ok thank, I know armorstand issue is not easy to fix, I open this issue because copy block, but it fix now, now close this.
